apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: image-build
spec:
  taskSpec:
    results:
      - name: first-ARTIFACT_OUTPUTS
        description: The first artifact built
        type: object
        properties:
          uri: {}
          digest: {}
      
      - name: second-ARTIFACT_OUTPUTS
        description: The second artifact built
        type: object
        properties:
          uri: {}
          digest: {}
          isBuildArtifact: {}
      
      - name: third-IMAGE_URL
        type: string
      - name: third-IMAGE_DIGEST
        type: string

      - name: IMAGES
        type: string

      - name: fourth-ARTIFACT_OUTPUTS
        type: object
        properties:
          uri: {}
          digest: {}
          isBuildArtifact: {}


    steps:
      - name: dummy-build
        image: bash:latest
        script: |
          echo -n "{\"uri\":\"gcr.io/foo/img1\", \"digest\":\"sha256:586789aa031fafc7d78a5393cdc772e0b55107ea54bb8bcf3f2cdac6c6da51ee\"}" > $(results.first-ARTIFACT_OUTPUTS.path)

          echo -n "{\"uri\":\"gcr.io/foo/img2\", \"digest\":\"sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5\", \"isBuildArtifact\":\"true\"}" > $(results.second-ARTIFACT_OUTPUTS.path)

          echo -n "gcr.io/foo/bar" | tee $(results.third-IMAGE_URL.path)
          echo -n "sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b6" | tee $(results.third-IMAGE_DIGEST.path)

          echo -n "gcr.io/test/img3@sha256:2996854378975c2f8011ddf0526975d1aaf1790b404da7aad4bf25293055bc8b" | tee $(results.IMAGES.path)

          echo -n "{\"uri\":\"gcr.io/test/img4\", \"digest\":\"sha256:basd-sha\", \"isBuildArtifact\":\"true\"}" > $(results.fourth-ARTIFACT_OUTPUTS.path)